# Generated by Django 3.2.3 on 2021-08-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('MW', 'MOST WATCHED'), ('RA', 'RECENTLY ADDED'), ('TR', 'TOP RATED')], max_length=2)),
                ('video', models.FileField(upload_to='')),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
